### PR TITLE
removed scrollbar from editor panel

### PR DESCRIPTION
**Pull request by SgtPooki**
The scrollbar is unnecessary with the minimap. 
# editor-holder only contains the code mirror instance, so if someone can make the "#editor-holder *" more specific than we should, but I am not sure what that would be.

### CODE REVIEW

**Comment by tyunderwood** [comment]
the scrollbar is still present, is there a way to remove it that I am not seeing?

**Comment by websiteduck** [comment]
I'm going to go ahead and merge this in but at some point I'd like to give people the option of seeing the scrollbar or not.

**Comment by tyunderwood** [comment]
a toggle would probably be the best idea, since this removed the horizontal scrollbar as well :/

**Comment by websiteduck** [comment]
Oops, if you update the extension the horizontal scrollbar should be back now

**Pull request merged**
